export { default as Cart } from './Cart'
export { default as Category } from './Category'
export { default as Categories } from './Categories'
export { default as EditCategory } from './EditCategory'
export { default as Checkout } from './Checkout'
export { default as AddProduct } from './AddProduct'
// export { default as EditCart } from './EditCart'
export { default as EditProduct } from './EditProduct'
export { default as Home } from './Home'
export { default as Login } from './Login'
export { default as Navbar } from './Navbar'
export { default as Products } from './Products'
export { default as Profile } from './Profile'
export { default as Register } from './Register'
export { default as Review } from './Review'
export { default as SingleProductView } from './SingleProductView'